# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1450, 991)
        Form.setMinimumSize(QtCore.QSize(1450, 736))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.logo_checkout = QtWidgets.QLabel(self.frame_2)
        self.logo_checkout.setGeometry(QtCore.QRect(20, 10, 80, 80))
        self.logo_checkout.setMinimumSize(QtCore.QSize(80, 80))
        self.logo_checkout.setMaximumSize(QtCore.QSize(80, 80))
        self.logo_checkout.setText("")
        self.logo_checkout.setPixmap(QtGui.QPixmap("UI_Files/Images/Logo.png"))
        self.logo_checkout.setScaledContents(True)
        self.logo_checkout.setObjectName("logo_checkout")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1200, 100))
        self.frame_5.setMinimumSize(QtCore.QSize(500, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.logo_checkout_2 = QtWidgets.QLabel(self.frame_5)
        self.logo_checkout_2.setGeometry(QtCore.QRect(20, 10, 80, 80))
        self.logo_checkout_2.setMinimumSize(QtCore.QSize(80, 80))
        self.logo_checkout_2.setMaximumSize(QtCore.QSize(80, 80))
        self.logo_checkout_2.setText("")
        self.logo_checkout_2.setPixmap(QtGui.QPixmap("UI_Files/Images/Logo.png"))
        self.logo_checkout_2.setScaledContents(True)
        self.logo_checkout_2.setObjectName("logo_checkout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(0, 107, 1192, 616))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet(
            "QFrame { \n"
            "   background-color: rgb(255, 255, 255);\n"
            "   border-radius: 7px;\n"
            "   border: 1px solid rgb(196, 205, 208);\n"
            "} "
        )
        self.tabWidget_2.setMovable(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.TPedidos_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.TPedidos_2.setFont(font)
        self.TPedidos_2.setObjectName("TPedidos_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.TPedidos_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.TPedidos_2)
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.treeWidget_3.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_3.headerItem().setFont(0, font)
        self.treeWidget_3.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_3.headerItem().setFont(1, font)
        self.treeWidget_3.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_3.headerItem().setFont(2, font)
        self.treeWidget_3.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_3.headerItem().setFont(3, font)
        self.horizontalLayout_6.addWidget(self.treeWidget_3)
        self.tabWidget_2.addTab(self.TPedidos_2, "")
        self.tEstoque_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.tEstoque_2.setFont(font)
        self.tEstoque_2.setObjectName("tEstoque_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tEstoque_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.tEstoque_2)
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.treeWidget_4.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_4.headerItem().setFont(0, font)
        self.treeWidget_4.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_4.headerItem().setFont(1, font)
        self.treeWidget_4.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_4.headerItem().setFont(2, font)
        self.treeWidget_4.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_4.headerItem().setFont(3, font)
        self.treeWidget_4.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_4.headerItem().setFont(4, font)
        self.treeWidget_4.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_4.headerItem().setFont(5, font)
        self.horizontalLayout_7.addWidget(self.treeWidget_4)
        self.tabWidget_2.addTab(self.tEstoque_2, "")
        self.tClientes_2 = QtWidgets.QWidget()
        self.tClientes_2.setObjectName("tClientes_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tClientes_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.twInventory_2 = QtWidgets.QTreeWidget(self.tClientes_2)
        self.twInventory_2.setObjectName("twInventory_2")
        self.twInventory_2.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twInventory_2.headerItem().setFont(0, font)
        self.twInventory_2.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twInventory_2.headerItem().setFont(1, font)
        self.twInventory_2.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twInventory_2.headerItem().setFont(2, font)
        self.twInventory_2.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twInventory_2.headerItem().setFont(3, font)
        self.twInventory_2.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twInventory_2.headerItem().setFont(4, font)
        self.twInventory_2.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twInventory_2.headerItem().setFont(5, font)
        self.horizontalLayout_8.addWidget(self.twInventory_2)
        self.tabWidget_2.addTab(self.tClientes_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "color: white;\n"
            "}"
        )
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 165))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_11.setStyleSheet(
            "QFrame { \n"
            "   background-color: rgb(245, 245, 245);\n"
            "   border-radius: 7px;\n"
            "   border: 1px solid rgb(196, 205, 208);\n"
            "} "
        )
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.l_vtotal_2 = QtWidgets.QLabel(self.frame_11)
        self.l_vtotal_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.l_vtotal_2.setFont(font)
        self.l_vtotal_2.setStyleSheet("border: 1px solid rgb(245,245,245);")
        self.l_vtotal_2.setObjectName("l_vtotal_2")
        self.gridLayout_5.addWidget(self.l_vtotal_2, 4, 0, 1, 1)
        self.l_nprod_2 = QtWidgets.QLabel(self.frame_11)
        self.l_nprod_2.setMinimumSize(QtCore.QSize(328, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_nprod_2.setFont(font)
        self.l_nprod_2.setStyleSheet("border: 1px solid rgb(245,245,245);\n" "")
        self.l_nprod_2.setObjectName("l_nprod_2")
        self.gridLayout_5.addWidget(self.l_nprod_2, 0, 0, 1, 2)
        self.l_qtd_2 = QtWidgets.QLabel(self.frame_11)
        self.l_qtd_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.l_qtd_2.setFont(font)
        self.l_qtd_2.setStyleSheet("border: 1px solid rgb(245,245,245);\n" "")
        self.l_qtd_2.setObjectName("l_qtd_2")
        self.gridLayout_5.addWidget(self.l_qtd_2, 3, 0, 1, 1)
        self.sb_qtd_2 = QtWidgets.QSpinBox(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.sb_qtd_2.setFont(font)
        self.sb_qtd_2.setObjectName("sb_qtd_2")
        self.gridLayout_5.addWidget(self.sb_qtd_2, 1, 1, 1, 1)
        self.ds_pa_2 = QtWidgets.QDoubleSpinBox(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.ds_pa_2.setFont(font)
        self.ds_pa_2.setObjectName("ds_pa_2")
        self.gridLayout_5.addWidget(self.ds_pa_2, 3, 1, 1, 1)
        self.l_vunit_2 = QtWidgets.QLabel(self.frame_11)
        self.l_vunit_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.l_vunit_2.setFont(font)
        self.l_vunit_2.setStyleSheet("border: 1px solid rgb(245,245,245);")
        self.l_vunit_2.setObjectName("l_vunit_2")
        self.gridLayout_5.addWidget(self.l_vunit_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 1px solid rgb(245,245,245);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.sb_qtd_alert_2 = QtWidgets.QSpinBox(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.sb_qtd_alert_2.setFont(font)
        self.sb_qtd_alert_2.setObjectName("sb_qtd_alert_2")
        self.gridLayout_5.addWidget(self.sb_qtd_alert_2, 2, 1, 1, 1)
        self.ds_psa_2 = QtWidgets.QDoubleSpinBox(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.ds_psa_2.setFont(font)
        self.ds_psa_2.setObjectName("ds_psa_2")
        self.gridLayout_5.addWidget(self.ds_psa_2, 4, 1, 2, 1)
        self.gridLayout_4.addWidget(self.frame_11, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_12.setStyleSheet(
            "QFrame { \n"
            "   background-color: rgb(245, 245, 245);\n"
            "   border-radius: 7px;\n"
            "   border: 1px solid rgb(196, 205, 208);\n"
            "} "
        )
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 1px solid rgb(245,245,245);\n" "")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.listView_2 = QtWidgets.QListView(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.listView_2.setFont(font)
        self.listView_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView_2.setObjectName("listView_2")
        self.gridLayout_6.addWidget(self.listView_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_12, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_4.setMinimumSize(QtCore.QSize(376, 45))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(60, 160, 181);\n"
            "color: white;\n"
            "}"
        )
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(
            "QFrame { \n"
            "   background-color: rgb(255, 255, 255);\n"
            "   border-radius: 7px;\n"
            "   border: 1px solid rgb(196, 205, 208);\n"
            "} "
        )
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.TPedidos = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.TPedidos.setFont(font)
        self.TPedidos.setObjectName("TPedidos")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TPedidos)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.TPedidos)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(1, font)
        self.treeWidget.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(2, font)
        self.treeWidget.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(3, font)
        self.treeWidget.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(3, font)
        self.horizontalLayout_3.addWidget(self.treeWidget)
        self.tabWidget.addTab(self.TPedidos, "")
        self.tEstoque = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.tEstoque.setFont(font)
        self.tEstoque.setObjectName("tEstoque")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tEstoque)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.twInventory = QtWidgets.QTreeWidget(self.tEstoque)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        self.twInventory.setFont(font)
        self.twInventory.setObjectName("twInventory")
        self.twInventory.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.twInventory.headerItem().setFont(0, font)
        self.twInventory.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.twInventory.headerItem().setFont(1, font)
        self.twInventory.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.twInventory.headerItem().setFont(2, font)
        self.twInventory.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.twInventory.headerItem().setFont(3, font)
        self.twInventory.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.twInventory.headerItem().setFont(4, font)
        self.twInventory.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.twInventory.headerItem().setFont(5, font)
        self.horizontalLayout_2.addWidget(self.twInventory)
        self.tabWidget.addTab(self.tEstoque, "")
        self.tClientes = QtWidgets.QWidget()
        self.tClientes.setObjectName("tClientes")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tClientes)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.twCustomers = QtWidgets.QTreeWidget(self.tClientes)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        self.twCustomers.setFont(font)
        self.twCustomers.setObjectName("twCustomers")
        self.twCustomers.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twCustomers.headerItem().setFont(0, font)
        self.twCustomers.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twCustomers.headerItem().setFont(1, font)
        self.twCustomers.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twCustomers.headerItem().setFont(2, font)
        self.twCustomers.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twCustomers.headerItem().setFont(3, font)
        self.twCustomers.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twCustomers.headerItem().setFont(4, font)
        self.twCustomers.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.twCustomers.headerItem().setFont(5, font)
        self.horizontalLayout_4.addWidget(self.twCustomers)
        self.tabWidget.addTab(self.tClientes, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 69))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_13.setFont(font)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.frame_13)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 55))
        self.pushButton.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(60, 160, 181);\n"
            "color: white;\n"
            "}\n"
            ""
        )
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_13)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(0, 55))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet(
            "QTextBrowser{\n"
            "background-color: rgb(255, 255, 255);\n"
            "border-radius: 7px;\n"
            "border: 1px solid rgb(196, 205, 208);\n"
            "padding-top: 3px;\n"
            "padding-left: 2px;\n"
            "}\n"
            ""
        )
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_9.addWidget(self.textBrowser_2)
        self.BtnRmvProduct = QtWidgets.QPushButton(self.frame_13)
        self.BtnRmvProduct.setMinimumSize(QtCore.QSize(220, 55))
        self.BtnRmvProduct.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BtnRmvProduct.setFont(font)
        self.BtnRmvProduct.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "color: white;\n"
            "}\n"
            ""
        )
        self.BtnRmvProduct.setObjectName("BtnRmvProduct")
        self.horizontalLayout_9.addWidget(self.BtnRmvProduct)
        self.BtnAddProduct = QtWidgets.QPushButton(self.frame_13)
        self.BtnAddProduct.setMinimumSize(QtCore.QSize(220, 55))
        self.BtnAddProduct.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BtnAddProduct.setFont(font)
        self.BtnAddProduct.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "color: white;\n"
            "}"
        )
        self.BtnAddProduct.setObjectName("BtnAddProduct")
        self.horizontalLayout_9.addWidget(self.BtnAddProduct)
        self.verticalLayout_2.addWidget(self.frame_13)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 165))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_8.setStyleSheet(
            "QFrame { \n"
            "   background-color: rgb(245, 245, 245);\n"
            "   border-radius: 7px;\n"
            "   border: 1px solid rgb(196, 205, 208);\n"
            "} "
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_vtotal = QtWidgets.QLabel(self.frame_8)
        self.l_vtotal.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.l_vtotal.setFont(font)
        self.l_vtotal.setStyleSheet("border: 1px solid rgb(245,245,245);")
        self.l_vtotal.setObjectName("l_vtotal")
        self.gridLayout_3.addWidget(self.l_vtotal, 4, 0, 1, 1)
        self.l_nprod = QtWidgets.QLabel(self.frame_8)
        self.l_nprod.setMinimumSize(QtCore.QSize(328, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l_nprod.setFont(font)
        self.l_nprod.setStyleSheet("border: 1px solid rgb(245,245,245);\n" "")
        self.l_nprod.setObjectName("l_nprod")
        self.gridLayout_3.addWidget(self.l_nprod, 0, 0, 1, 2)
        self.l_qtd = QtWidgets.QLabel(self.frame_8)
        self.l_qtd.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.l_qtd.setFont(font)
        self.l_qtd.setStyleSheet("border: 1px solid rgb(245,245,245);\n" "")
        self.l_qtd.setObjectName("l_qtd")
        self.gridLayout_3.addWidget(self.l_qtd, 3, 0, 1, 1)
        self.sb_qtd = QtWidgets.QSpinBox(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.sb_qtd.setFont(font)
        self.sb_qtd.setObjectName("sb_qtd")
        self.gridLayout_3.addWidget(self.sb_qtd, 1, 1, 1, 1)
        self.ds_pa = QtWidgets.QDoubleSpinBox(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.ds_pa.setFont(font)
        self.ds_pa.setObjectName("ds_pa")
        self.gridLayout_3.addWidget(self.ds_pa, 3, 1, 1, 1)
        self.l_vunit = QtWidgets.QLabel(self.frame_8)
        self.l_vunit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.l_vunit.setFont(font)
        self.l_vunit.setStyleSheet("border: 1px solid rgb(245,245,245);")
        self.l_vunit.setObjectName("l_vunit")
        self.gridLayout_3.addWidget(self.l_vunit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 1px solid rgb(245,245,245);")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.sb_qtd_alert = QtWidgets.QSpinBox(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.sb_qtd_alert.setFont(font)
        self.sb_qtd_alert.setObjectName("sb_qtd_alert")
        self.gridLayout_3.addWidget(self.sb_qtd_alert, 2, 1, 1, 1)
        self.ds_psa = QtWidgets.QDoubleSpinBox(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.ds_psa.setFont(font)
        self.ds_psa.setObjectName("ds_psa")
        self.gridLayout_3.addWidget(self.ds_psa, 4, 1, 2, 1)
        self.gridLayout.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_6.setStyleSheet(
            "QFrame { \n"
            "   background-color: rgb(245, 245, 245);\n"
            "   border-radius: 7px;\n"
            "   border: 1px solid rgb(196, 205, 208);\n"
            "} "
        )
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 1px solid rgb(245,245,245);\n" "")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.listView = QtWidgets.QListWidget(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.listView.setFont(font)
        self.listView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 69))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_2.setMinimumSize(QtCore.QSize(350, 55))
        self.pushButton_2.setMaximumSize(QtCore.QSize(350, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(60, 160, 181);\n"
            "color: white;\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.frame_15, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.BtnShowHideKbd = QtWidgets.QPushButton(Form)
        self.BtnShowHideKbd.setStyleSheet(
            "QPushButton{\n"
            "background-color: rgb(245, 245, 245);\n"
            "border-radius: 7px;\n"
            "border-styles: outset;\n"
            "}\n"
            ""
        )
        self.BtnShowHideKbd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("icons/keyboard_double_arrow_up.svg"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.BtnShowHideKbd.setIcon(icon)
        self.BtnShowHideKbd.setCheckable(True)
        self.BtnShowHideKbd.setChecked(False)
        self.BtnShowHideKbd.setObjectName("BtnShowHideKbd")
        self.verticalLayout.addWidget(self.BtnShowHideKbd)
        self.frame_16 = QtWidgets.QFrame(Form)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setMinimumSize(QtCore.QSize(290, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Btn_x = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_x.setFont(font)
        self.Btn_x.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_x.setObjectName("Btn_x")
        self.gridLayout_7.addWidget(self.Btn_x, 3, 1, 1, 1)
        self.Btn_e = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_e.setFont(font)
        self.Btn_e.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_e.setObjectName("Btn_e")
        self.gridLayout_7.addWidget(self.Btn_e, 1, 2, 1, 1)
        self.Btn_z = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_z.setFont(font)
        self.Btn_z.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_z.setObjectName("Btn_z")
        self.gridLayout_7.addWidget(self.Btn_z, 3, 0, 1, 1)
        self.Btn_c = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_c.setFont(font)
        self.Btn_c.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_c.setObjectName("Btn_c")
        self.gridLayout_7.addWidget(self.Btn_c, 3, 2, 1, 1)
        self.Btn_q = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_q.setFont(font)
        self.Btn_q.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_q.setObjectName("Btn_q")
        self.gridLayout_7.addWidget(self.Btn_q, 1, 0, 1, 1)
        self.Btn_1 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_1.setFont(font)
        self.Btn_1.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_1.setObjectName("Btn_1")
        self.gridLayout_7.addWidget(self.Btn_1, 0, 0, 1, 1)
        self.Btn_2 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_2.setFont(font)
        self.Btn_2.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_2.setObjectName("Btn_2")
        self.gridLayout_7.addWidget(self.Btn_2, 0, 1, 1, 1)
        self.Btn_w = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_w.setFont(font)
        self.Btn_w.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_w.setObjectName("Btn_w")
        self.gridLayout_7.addWidget(self.Btn_w, 1, 1, 1, 1)
        self.Btn_3 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_3.setFont(font)
        self.Btn_3.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_3.setObjectName("Btn_3")
        self.gridLayout_7.addWidget(self.Btn_3, 0, 2, 1, 1)
        self.Btn_caps = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_caps.setFont(font)
        self.Btn_caps.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_caps.setObjectName("Btn_caps")
        self.gridLayout_7.addWidget(self.Btn_caps, 4, 0, 1, 3)
        self.Btn_a = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_a.setFont(font)
        self.Btn_a.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_a.setObjectName("Btn_a")
        self.gridLayout_7.addWidget(self.Btn_a, 2, 0, 1, 1)
        self.Btn_s = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_s.setFont(font)
        self.Btn_s.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_s.setObjectName("Btn_s")
        self.gridLayout_7.addWidget(self.Btn_s, 2, 1, 1, 1)
        self.Btn_d = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_d.setFont(font)
        self.Btn_d.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}\n"
            ""
        )
        self.Btn_d.setObjectName("Btn_d")
        self.gridLayout_7.addWidget(self.Btn_d, 2, 2, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        self.frame_19.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Btn_space = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_space.setFont(font)
        self.Btn_space.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_space.setObjectName("Btn_space")
        self.gridLayout_8.addWidget(self.Btn_space, 4, 0, 1, 4)
        self.Btn_f = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_f.setFont(font)
        self.Btn_f.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_f.setObjectName("Btn_f")
        self.gridLayout_8.addWidget(self.Btn_f, 2, 0, 1, 1)
        self.Btn_4 = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_4.setFont(font)
        self.Btn_4.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_4.setObjectName("Btn_4")
        self.gridLayout_8.addWidget(self.Btn_4, 0, 0, 1, 1)
        self.Btn_y = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_y.setFont(font)
        self.Btn_y.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_y.setObjectName("Btn_y")
        self.gridLayout_8.addWidget(self.Btn_y, 1, 2, 1, 1)
        self.Btn_b = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_b.setFont(font)
        self.Btn_b.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_b.setObjectName("Btn_b")
        self.gridLayout_8.addWidget(self.Btn_b, 3, 1, 1, 1)
        self.Btn_j = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_j.setFont(font)
        self.Btn_j.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_j.setObjectName("Btn_j")
        self.gridLayout_8.addWidget(self.Btn_j, 2, 3, 1, 1)
        self.Btn_n = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_n.setFont(font)
        self.Btn_n.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_n.setObjectName("Btn_n")
        self.gridLayout_8.addWidget(self.Btn_n, 3, 2, 1, 1)
        self.Btn_r = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_r.setFont(font)
        self.Btn_r.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}\n"
            ""
        )
        self.Btn_r.setObjectName("Btn_r")
        self.gridLayout_8.addWidget(self.Btn_r, 1, 0, 1, 1)
        self.Btn_m = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_m.setFont(font)
        self.Btn_m.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_m.setObjectName("Btn_m")
        self.gridLayout_8.addWidget(self.Btn_m, 3, 3, 1, 1)
        self.Btn_6 = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_6.setFont(font)
        self.Btn_6.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_6.setObjectName("Btn_6")
        self.gridLayout_8.addWidget(self.Btn_6, 0, 2, 1, 1)
        self.Btn_u = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_u.setFont(font)
        self.Btn_u.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_u.setObjectName("Btn_u")
        self.gridLayout_8.addWidget(self.Btn_u, 1, 3, 1, 1)
        self.Btn_g = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_g.setFont(font)
        self.Btn_g.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_g.setObjectName("Btn_g")
        self.gridLayout_8.addWidget(self.Btn_g, 2, 1, 1, 1)
        self.Btn_v = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_v.setFont(font)
        self.Btn_v.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_v.setObjectName("Btn_v")
        self.gridLayout_8.addWidget(self.Btn_v, 3, 0, 1, 1)
        self.Btn_t = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_t.setFont(font)
        self.Btn_t.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_t.setObjectName("Btn_t")
        self.gridLayout_8.addWidget(self.Btn_t, 1, 1, 1, 1)
        self.Btn_5 = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_5.setFont(font)
        self.Btn_5.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_5.setObjectName("Btn_5")
        self.gridLayout_8.addWidget(self.Btn_5, 0, 1, 1, 1)
        self.Btn_7 = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_7.setFont(font)
        self.Btn_7.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_7.setObjectName("Btn_7")
        self.gridLayout_8.addWidget(self.Btn_7, 0, 3, 1, 1)
        self.Btn_h = QtWidgets.QPushButton(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_h.setFont(font)
        self.Btn_h.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_h.setObjectName("Btn_h")
        self.gridLayout_8.addWidget(self.Btn_h, 2, 2, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_19)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Btn_o = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_o.setFont(font)
        self.Btn_o.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_o.setObjectName("Btn_o")
        self.gridLayout_9.addWidget(self.Btn_o, 1, 1, 1, 1)
        self.Btn_p = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_p.setFont(font)
        self.Btn_p.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_p.setObjectName("Btn_p")
        self.gridLayout_9.addWidget(self.Btn_p, 1, 2, 1, 1)
        self.Btn_pt = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_pt.setFont(font)
        self.Btn_pt.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_pt.setObjectName("Btn_pt")
        self.gridLayout_9.addWidget(self.Btn_pt, 3, 1, 1, 1)
        self.Btn_9 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_9.setFont(font)
        self.Btn_9.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_9.setObjectName("Btn_9")
        self.gridLayout_9.addWidget(self.Btn_9, 0, 1, 1, 1)
        self.Btn_0 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_0.setFont(font)
        self.Btn_0.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_0.setObjectName("Btn_0")
        self.gridLayout_9.addWidget(self.Btn_0, 0, 2, 1, 1)
        self.Btn_8 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_8.setFont(font)
        self.Btn_8.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_8.setObjectName("Btn_8")
        self.gridLayout_9.addWidget(self.Btn_8, 0, 0, 1, 1)
        self.Btn_i = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_i.setFont(font)
        self.Btn_i.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_i.setObjectName("Btn_i")
        self.gridLayout_9.addWidget(self.Btn_i, 1, 0, 1, 1)
        self.Btn_ar = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_ar.setFont(font)
        self.Btn_ar.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_ar.setObjectName("Btn_ar")
        self.gridLayout_9.addWidget(self.Btn_ar, 3, 0, 1, 1)
        self.Btn_und = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_und.setFont(font)
        self.Btn_und.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_und.setObjectName("Btn_und")
        self.gridLayout_9.addWidget(self.Btn_und, 3, 2, 1, 1)
        self.Btn_back = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_back.setFont(font)
        self.Btn_back.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_back.setObjectName("Btn_back")
        self.gridLayout_9.addWidget(self.Btn_back, 7, 0, 1, 3)
        self.Btn_k = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_k.setFont(font)
        self.Btn_k.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_k.setObjectName("Btn_k")
        self.gridLayout_9.addWidget(self.Btn_k, 2, 0, 1, 1)
        self.Btn_l = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_l.setFont(font)
        self.Btn_l.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_l.setObjectName("Btn_l")
        self.gridLayout_9.addWidget(self.Btn_l, 2, 1, 1, 1)
        self.Btn_c_ = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_c_.setFont(font)
        self.Btn_c_.setStyleSheet(
            "QPushButton{\n"
            "border-radius: 7px;\n"
            "background-color: rgb(110, 200, 220);\n"
            "border-style: outset;\n"
            "color: white;\n"
            "}"
        )
        self.Btn_c_.setObjectName("Btn_c_")
        self.gridLayout_9.addWidget(self.Btn_c_, 2, 2, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_17)
        self.verticalLayout.addWidget(self.frame_16)

        self.twCustomers.itemClicked.connect(self.on_customers_itemClicked)

        self.twInventory.itemClicked.connect(self.on_products_itemClicked)

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.BtnShowHideKbd.toggled["bool"].connect(self.frame_16.setVisible)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.product_id = 0

    def on_customers_itemClicked(self, item, column):
        print(item.text(i) for i in range(item.columnCount()))

    def on_products_itemClicked(self, item, column):
        item_data = [item.text(i) for i in range(item.columnCount())]
        self.product_id = item_data[0]
        self.l_nprod.setText(item_data[1])
        self.sb_qtd.setValue(int(item_data[2]))
        self.sb_qtd_alert.setValue(int(float(item_data[3])))
        self.ds_pa.setValue(float(item_data[4]))
        self.ds_psa.setValue(float(item_data[5]))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_3.headerItem().setText(0, _translate("Form", "Nº Pedido"))
        self.treeWidget_3.headerItem().setText(1, _translate("Form", "Usuário"))
        self.treeWidget_3.headerItem().setText(2, _translate("Form", "Cod. Produto"))
        self.treeWidget_3.headerItem().setText(3, _translate("Form", "Quantidade"))
        self.treeWidget_3.headerItem().setText(4, _translate("Form", "Valor"))
        self.tabWidget_2.setTabText(
            self.tabWidget_2.indexOf(self.TPedidos_2), _translate("Form", "Pedidos")
        )
        self.treeWidget_4.headerItem().setText(0, _translate("Form", "ID"))
        self.treeWidget_4.headerItem().setText(1, _translate("Form", "Nome do Produto"))
        self.treeWidget_4.headerItem().setText(2, _translate("Form", "Quantidade"))
        self.treeWidget_4.headerItem().setText(
            3, _translate("Form", "Quantidade (Alerta)")
        )
        self.treeWidget_4.headerItem().setText(
            4, _translate("Form", "Preço Afiliados (R$)")
        )
        self.treeWidget_4.headerItem().setText(
            5, _translate("Form", "Preço Sem Afiliação (R$)")
        )
        self.tabWidget_2.setTabText(
            self.tabWidget_2.indexOf(self.tEstoque_2), _translate("Form", "Estoque")
        )
        self.twInventory_2.headerItem().setText(0, _translate("Form", "ID"))
        self.twInventory_2.headerItem().setText(1, _translate("Form", "Nome"))
        self.twInventory_2.headerItem().setText(2, _translate("Form", "Sobrenome"))
        self.twInventory_2.headerItem().setText(3, _translate("Form", "CPF"))
        self.twInventory_2.headerItem().setText(4, _translate("Form", "Telefone"))
        self.twInventory_2.headerItem().setText(5, _translate("Form", "E-mail"))
        self.tabWidget_2.setTabText(
            self.tabWidget_2.indexOf(self.tClientes_2), _translate("Form", "Clientes")
        )
        self.pushButton_3.setText(_translate("Form", "Voltar"))
        self.l_vtotal_2.setText(_translate("Form", "Preço sem Afiliação"))
        self.l_nprod_2.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Nome do Produto</span></p></body></html>',
            )
        )
        self.l_qtd_2.setText(_translate("Form", "Preço Afiliados"))
        self.l_vunit_2.setText(_translate("Form", "Quantidade"))
        self.label_3.setText(_translate("Form", "Quantidade (Alerta)"))
        self.label_4.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center"><span style=" font-size:12pt; font-weight:600;">Produtos em Alerta</span></p></body></html>',
            )
        )
        self.pushButton_4.setText(_translate("Form", "Salvar"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Nº Pedido"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "Usuário"))
        self.treeWidget.headerItem().setText(2, _translate("Form", "Cod. Produto"))
        self.treeWidget.headerItem().setText(3, _translate("Form", "Quantidade"))
        self.treeWidget.headerItem().setText(4, _translate("Form", "Valor"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.TPedidos), _translate("Form", "Pedidos")
        )
        self.twInventory.headerItem().setText(0, _translate("Form", "ID"))
        self.twInventory.headerItem().setText(1, _translate("Form", "Nome do Produto"))
        self.twInventory.headerItem().setText(2, _translate("Form", "Quantidade"))
        self.twInventory.headerItem().setText(
            3, _translate("Form", "Quantidade (Alerta)")
        )
        self.twInventory.headerItem().setText(
            4, _translate("Form", "Preço Afiliados (R$)")
        )
        self.twInventory.headerItem().setText(
            5, _translate("Form", "Preço Sem Afiliação (R$)")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tEstoque), _translate("Form", "Estoque")
        )
        self.twCustomers.headerItem().setText(0, _translate("Form", "ID"))
        self.twCustomers.headerItem().setText(1, _translate("Form", "Nome"))
        self.twCustomers.headerItem().setText(2, _translate("Form", "Sobrenome"))
        self.twCustomers.headerItem().setText(3, _translate("Form", "CPF"))
        self.twCustomers.headerItem().setText(4, _translate("Form", "Telefone"))
        self.twCustomers.headerItem().setText(5, _translate("Form", "E-mail"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tClientes), _translate("Form", "Clientes")
        )
        self.pushButton.setText(_translate("Form", "Voltar"))
        self.textBrowser_2.setHtml(
            _translate(
                "Form",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Poppins'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Nome do Produto</p></body></html>',
            )
        )
        self.BtnRmvProduct.setText(_translate("Form", "Remover Produto"))
        self.BtnAddProduct.setText(_translate("Form", "Adicionar Produto"))
        self.l_vtotal.setText(_translate("Form", "Preço sem Afiliação"))
        self.l_nprod.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Nome do Produto</span></p></body></html>',
            )
        )
        self.l_qtd.setText(_translate("Form", "Preço Afiliados"))
        self.l_vunit.setText(_translate("Form", "Quantidade"))
        self.label.setText(_translate("Form", "Quantidade (Alerta)"))
        self.label_2.setText(
            _translate(
                "Form",
                '<html><head/><body><p align="center"><span style=" font-size:12pt; font-weight:600;">Produtos em Alerta</span></p></body></html>',
            )
        )
        self.pushButton_2.setText(_translate("Form", "Salvar"))
        self.BtnShowHideKbd.setToolTip(
            _translate(
                "Form",
                '<html><head/><body><p><img src=":/newPrefix/keyboard_double_arrow_up.svg"/></p></body></html>',
            )
        )
        self.Btn_x.setText(_translate("Form", "x"))
        self.Btn_e.setText(_translate("Form", "e"))
        self.Btn_z.setText(_translate("Form", "z"))
        self.Btn_c.setText(_translate("Form", "c"))
        self.Btn_q.setText(_translate("Form", "q"))
        self.Btn_1.setText(_translate("Form", "1"))
        self.Btn_2.setText(_translate("Form", "2"))
        self.Btn_w.setText(_translate("Form", "w"))
        self.Btn_3.setText(_translate("Form", "3"))
        self.Btn_caps.setText(_translate("Form", "CAPSLOCK"))
        self.Btn_a.setText(_translate("Form", "a"))
        self.Btn_s.setText(_translate("Form", "s"))
        self.Btn_d.setText(_translate("Form", "d"))
        self.Btn_space.setText(_translate("Form", "Space"))
        self.Btn_f.setText(_translate("Form", "f"))
        self.Btn_4.setText(_translate("Form", "4"))
        self.Btn_y.setText(_translate("Form", "y"))
        self.Btn_b.setText(_translate("Form", "b"))
        self.Btn_j.setText(_translate("Form", "j"))
        self.Btn_n.setText(_translate("Form", "n"))
        self.Btn_r.setText(_translate("Form", "r"))
        self.Btn_m.setText(_translate("Form", "m"))
        self.Btn_6.setText(_translate("Form", "6"))
        self.Btn_u.setText(_translate("Form", "u"))
        self.Btn_g.setText(_translate("Form", "g"))
        self.Btn_v.setText(_translate("Form", "v"))
        self.Btn_t.setText(_translate("Form", "t"))
        self.Btn_5.setText(_translate("Form", "5"))
        self.Btn_7.setText(_translate("Form", "7"))
        self.Btn_h.setText(_translate("Form", "h"))
        self.Btn_o.setText(_translate("Form", "o"))
        self.Btn_p.setText(_translate("Form", "p"))
        self.Btn_pt.setText(_translate("Form", "."))
        self.Btn_9.setText(_translate("Form", "9"))
        self.Btn_0.setText(_translate("Form", "0"))
        self.Btn_8.setText(_translate("Form", "8"))
        self.Btn_i.setText(_translate("Form", "i"))
        self.Btn_ar.setText(_translate("Form", "@"))
        self.Btn_und.setText(_translate("Form", "_"))
        self.Btn_back.setText(_translate("Form", "Backspace"))
        self.Btn_k.setText(_translate("Form", "k"))
        self.Btn_l.setText(_translate("Form", "l"))
        self.Btn_c_.setText(_translate("Form", "ç"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
