# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1005, 1000)
        Form.setMinimumSize(QtCore.QSize(1005, 736))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 110))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_register = QtWidgets.QLabel(self.frame_4)
        self.logo_register.setMinimumSize(QtCore.QSize(80, 80))
        self.logo_register.setMaximumSize(QtCore.QSize(80, 80))
        self.logo_register.setText("")
        self.logo_register.setPixmap(QtGui.QPixmap("UI_Files/Images/Logo.png"))
        self.logo_register.setScaledContents(True)
        self.logo_register.setObjectName("logo_register")
        self.horizontalLayout_3.addWidget(self.logo_register)
        spacerItem = QtWidgets.QSpacerItem(822, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setMinimumSize(QtCore.QSize(600, 455))
        self.frame_12.setMaximumSize(QtCore.QSize(580, 600))
        self.frame_12.setStyleSheet("QFrame { \n"
"   background-color: rgb(245, 245, 245);\n"
"   border-radius: 7px;\n"
"   border: 1px solid rgb(196, 205, 208);\n"
"} ")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_12)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setStyleSheet("border: 1px solid rgb(245, 245, 245);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lNome = QtWidgets.QLabel(self.frame_8)
        self.lNome.setMinimumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.lNome.setFont(font)
        self.lNome.setObjectName("lNome")
        self.horizontalLayout_5.addWidget(self.lNome)
        self.txtNome = QtWidgets.QTextBrowser(self.frame_8)
        self.txtNome.setMinimumSize(QtCore.QSize(200, 0))
        self.txtNome.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.txtNome.setFont(font)
        self.txtNome.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"border: 1px solid rgb(196, 205, 208);\n"
"padding-top: 3px;\n"
"padding-left: 2px;\n"
"}\n"
"")
        self.txtNome.setObjectName("txtNome")
        self.horizontalLayout_5.addWidget(self.txtNome)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_12)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_9.setStyleSheet("border: 1px solid rgb(245, 245, 245);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lSobrenome = QtWidgets.QLabel(self.frame_9)
        self.lSobrenome.setMinimumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.lSobrenome.setFont(font)
        self.lSobrenome.setObjectName("lSobrenome")
        self.horizontalLayout_6.addWidget(self.lSobrenome)
        self.txtSobrenome = QtWidgets.QTextBrowser(self.frame_9)
        self.txtSobrenome.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.txtSobrenome.setFont(font)
        self.txtSobrenome.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"border: 1px solid rgb(196, 205, 208);\n"
"padding-top: 3px;\n"
"padding-left: 2px;\n"
"}\n"
"")
        self.txtSobrenome.setObjectName("txtSobrenome")
        self.horizontalLayout_6.addWidget(self.txtSobrenome)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_12)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_10.setStyleSheet("border: 1px solid rgb(245, 245, 245);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.l_CPF = QtWidgets.QLabel(self.frame_10)
        self.l_CPF.setMinimumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.l_CPF.setFont(font)
        self.l_CPF.setObjectName("l_CPF")
        self.horizontalLayout_7.addWidget(self.l_CPF)
        self.txtCPF = QtWidgets.QTextBrowser(self.frame_10)
        self.txtCPF.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.txtCPF.setFont(font)
        self.txtCPF.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"border: 1px solid rgb(196, 205, 208);\n"
"padding-top: 3px;\n"
"padding-left: 2px;\n"
"}\n"
"")
        self.txtCPF.setObjectName("txtCPF")
        self.horizontalLayout_7.addWidget(self.txtCPF)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_12)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_11.setStyleSheet("border: 1px solid rgb(245, 245, 245);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.l_tel = QtWidgets.QLabel(self.frame_11)
        self.l_tel.setMinimumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.l_tel.setFont(font)
        self.l_tel.setObjectName("l_tel")
        self.horizontalLayout_8.addWidget(self.l_tel)
        self.txtTel = QtWidgets.QTextBrowser(self.frame_11)
        self.txtTel.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.txtTel.setFont(font)
        self.txtTel.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"border: 1px solid rgb(196, 205, 208);\n"
"padding-top: 3px;\n"
"padding-left: 2px;\n"
"}\n"
"")
        self.txtTel.setObjectName("txtTel")
        self.horizontalLayout_8.addWidget(self.txtTel)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_13.setStyleSheet("border: 1px solid rgb(245, 245, 245);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.l_email = QtWidgets.QLabel(self.frame_13)
        self.l_email.setMinimumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.l_email.setFont(font)
        self.l_email.setObjectName("l_email")
        self.horizontalLayout_9.addWidget(self.l_email)
        self.txtEmail = QtWidgets.QTextBrowser(self.frame_13)
        self.txtEmail.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"border: 1px solid rgb(196, 205, 208);\n"
"padding-top: 3px;\n"
"padding-left: 2px;\n"
"}\n"
"")
        self.txtEmail.setObjectName("txtEmail")
        self.horizontalLayout_9.addWidget(self.txtEmail)
        self.verticalLayout.addWidget(self.frame_13)
        self.horizontalLayout_4.addWidget(self.frame_12)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnVoltar = QtWidgets.QPushButton(self.frame_2)
        self.btnVoltar.setMinimumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnVoltar.setFont(font)
        self.btnVoltar.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"color: white;\n"
"}")
        self.btnVoltar.setObjectName("btnVoltar")
        self.horizontalLayout_2.addWidget(self.btnVoltar)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.btn_register = QtWidgets.QPushButton(self.frame_2)
        self.btn_register.setMinimumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(60, 160, 181);\n"
"color: white\n"
"}")
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout_2.addWidget(self.btn_register)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.btn_keyboard = QtWidgets.QPushButton(self.frame)
        self.btn_keyboard.setStyleSheet("QPushButton{\n"
"background-color: rgb(245, 245, 245);\n"
"border-radius: 7px;\n"
"border-styles: outset;\n"
"}\n"
"")
        self.btn_keyboard.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/keyboard_double_arrow_up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_keyboard.setIcon(icon)
        self.btn_keyboard.setIconSize(QtCore.QSize(25, 25))
        self.btn_keyboard.setCheckable(True)
        self.btn_keyboard.setChecked(False)
        self.btn_keyboard.setObjectName("btn_keyboard")
        self.verticalLayout_2.addWidget(self.btn_keyboard)
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setMinimumSize(QtCore.QSize(450, 0))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_14 = QtWidgets.QFrame(self.frame_15)
        self.frame_14.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.frame_14.setFont(font)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout.setObjectName("gridLayout")
        self.key_x = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_x.setFont(font)
        self.key_x.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_x.setObjectName("key_x")
        self.gridLayout.addWidget(self.key_x, 3, 1, 1, 1)
        self.key_a = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_a.setFont(font)
        self.key_a.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_a.setObjectName("key_a")
        self.gridLayout.addWidget(self.key_a, 2, 0, 1, 1)
        self.key_3 = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_3.setFont(font)
        self.key_3.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_3.setObjectName("key_3")
        self.gridLayout.addWidget(self.key_3, 0, 2, 1, 1)
        self.key_z = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_z.setFont(font)
        self.key_z.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_z.setObjectName("key_z")
        self.gridLayout.addWidget(self.key_z, 3, 0, 1, 1)
        self.key_q = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_q.setFont(font)
        self.key_q.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_q.setObjectName("key_q")
        self.gridLayout.addWidget(self.key_q, 1, 0, 1, 1)
        self.key_e = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_e.setFont(font)
        self.key_e.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_e.setObjectName("key_e")
        self.gridLayout.addWidget(self.key_e, 1, 2, 1, 1)
        self.key_1 = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_1.setFont(font)
        self.key_1.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_1.setObjectName("key_1")
        self.gridLayout.addWidget(self.key_1, 0, 0, 1, 1)
        self.key_2 = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_2.setFont(font)
        self.key_2.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_2.setObjectName("key_2")
        self.gridLayout.addWidget(self.key_2, 0, 1, 1, 1)
        self.key_c = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_c.setFont(font)
        self.key_c.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_c.setObjectName("key_c")
        self.gridLayout.addWidget(self.key_c, 3, 2, 1, 1)
        self.key_w = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_w.setFont(font)
        self.key_w.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_w.setObjectName("key_w")
        self.gridLayout.addWidget(self.key_w, 1, 1, 1, 1)
        self.key_d = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_d.setFont(font)
        self.key_d.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_d.setObjectName("key_d")
        self.gridLayout.addWidget(self.key_d, 2, 2, 1, 1)
        self.key_s = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_s.setFont(font)
        self.key_s.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_s.setObjectName("key_s")
        self.gridLayout.addWidget(self.key_s, 2, 1, 1, 1)
        self.key_caps = QtWidgets.QPushButton(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_caps.setFont(font)
        self.key_caps.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_caps.setObjectName("key_caps")
        self.gridLayout.addWidget(self.key_caps, 4, 0, 1, 3)
        self.horizontalLayout_11.addWidget(self.frame_14)
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_17.setFont(font)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.key_f = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_f.setFont(font)
        self.key_f.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_f.setObjectName("key_f")
        self.gridLayout_2.addWidget(self.key_f, 3, 0, 1, 1)
        self.key_m = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_m.setFont(font)
        self.key_m.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_m.setObjectName("key_m")
        self.gridLayout_2.addWidget(self.key_m, 4, 3, 1, 1)
        self.key_u = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_u.setFont(font)
        self.key_u.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_u.setObjectName("key_u")
        self.gridLayout_2.addWidget(self.key_u, 1, 3, 1, 1)
        self.key_r = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_r.setFont(font)
        self.key_r.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_r.setObjectName("key_r")
        self.gridLayout_2.addWidget(self.key_r, 1, 0, 1, 1)
        self.key_7 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_7.setFont(font)
        self.key_7.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_7.setObjectName("key_7")
        self.gridLayout_2.addWidget(self.key_7, 0, 3, 1, 1)
        self.key_v = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_v.setFont(font)
        self.key_v.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_v.setObjectName("key_v")
        self.gridLayout_2.addWidget(self.key_v, 4, 0, 1, 1)
        self.key_5 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_5.setFont(font)
        self.key_5.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_5.setObjectName("key_5")
        self.gridLayout_2.addWidget(self.key_5, 0, 1, 1, 1)
        self.key_t = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_t.setFont(font)
        self.key_t.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_t.setObjectName("key_t")
        self.gridLayout_2.addWidget(self.key_t, 1, 1, 1, 1)
        self.key_g = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_g.setFont(font)
        self.key_g.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_g.setObjectName("key_g")
        self.gridLayout_2.addWidget(self.key_g, 3, 1, 1, 1)
        self.key_j = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_j.setFont(font)
        self.key_j.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_j.setObjectName("key_j")
        self.gridLayout_2.addWidget(self.key_j, 3, 3, 1, 1)
        self.key_4 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_4.setFont(font)
        self.key_4.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_4.setObjectName("key_4")
        self.gridLayout_2.addWidget(self.key_4, 0, 0, 1, 1)
        self.key_6 = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_6.setFont(font)
        self.key_6.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_6.setObjectName("key_6")
        self.gridLayout_2.addWidget(self.key_6, 0, 2, 1, 1)
        self.key_space = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_space.setFont(font)
        self.key_space.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(60, 160, 181);\n"
"color: white\n"
"}")
        self.key_space.setObjectName("key_space")
        self.gridLayout_2.addWidget(self.key_space, 5, 0, 1, 4)
        self.key_h = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_h.setFont(font)
        self.key_h.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_h.setObjectName("key_h")
        self.gridLayout_2.addWidget(self.key_h, 3, 2, 1, 1)
        self.key_y = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_y.setFont(font)
        self.key_y.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_y.setObjectName("key_y")
        self.gridLayout_2.addWidget(self.key_y, 1, 2, 1, 1)
        self.key_n = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_n.setFont(font)
        self.key_n.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_n.setObjectName("key_n")
        self.gridLayout_2.addWidget(self.key_n, 4, 2, 1, 1)
        self.key_b = QtWidgets.QPushButton(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_b.setFont(font)
        self.key_b.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_b.setObjectName("key_b")
        self.gridLayout_2.addWidget(self.key_b, 4, 1, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.frame_18.setFont(font)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.key_l = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_l.setFont(font)
        self.key_l.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_l.setObjectName("key_l")
        self.gridLayout_3.addWidget(self.key_l, 3, 1, 1, 1)
        self.key_c_ = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_c_.setFont(font)
        self.key_c_.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_c_.setObjectName("key_c_")
        self.gridLayout_3.addWidget(self.key_c_, 3, 2, 1, 1)
        self.key_ar = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_ar.setFont(font)
        self.key_ar.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_ar.setObjectName("key_ar")
        self.gridLayout_3.addWidget(self.key_ar, 4, 0, 1, 1)
        self.key_pt = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_pt.setFont(font)
        self.key_pt.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_pt.setObjectName("key_pt")
        self.gridLayout_3.addWidget(self.key_pt, 4, 1, 1, 1)
        self.key_und = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_und.setFont(font)
        self.key_und.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_und.setObjectName("key_und")
        self.gridLayout_3.addWidget(self.key_und, 4, 2, 1, 1)
        self.key_p = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_p.setFont(font)
        self.key_p.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_p.setObjectName("key_p")
        self.gridLayout_3.addWidget(self.key_p, 2, 2, 1, 1)
        self.key_i = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_i.setFont(font)
        self.key_i.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_i.setObjectName("key_i")
        self.gridLayout_3.addWidget(self.key_i, 2, 0, 1, 1)
        self.key_o = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_o.setFont(font)
        self.key_o.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_o.setObjectName("key_o")
        self.gridLayout_3.addWidget(self.key_o, 2, 1, 1, 1)
        self.key_k = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_k.setFont(font)
        self.key_k.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_k.setObjectName("key_k")
        self.gridLayout_3.addWidget(self.key_k, 3, 0, 1, 1)
        self.key_9 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_9.setFont(font)
        self.key_9.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_9.setObjectName("key_9")
        self.gridLayout_3.addWidget(self.key_9, 0, 1, 1, 1)
        self.key_0 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_0.setFont(font)
        self.key_0.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_0.setObjectName("key_0")
        self.gridLayout_3.addWidget(self.key_0, 0, 2, 1, 1)
        self.key_8 = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_8.setFont(font)
        self.key_8.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}\n"
"")
        self.key_8.setObjectName("key_8")
        self.gridLayout_3.addWidget(self.key_8, 0, 0, 1, 1)
        self.key_ = QtWidgets.QPushButton(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.key_.setFont(font)
        self.key_.setStyleSheet("QPushButton{\n"
"border-radius: 7px;\n"
"background-color: rgb(110, 200, 220);\n"
"border-style: outset;\n"
"color: white;\n"
"}")
        self.key_.setText("Backspace")
        self.key_.setObjectName("key_bck")
        self.gridLayout_3.addWidget(self.key_, 5, 0, 1, 3)
        self.horizontalLayout_11.addWidget(self.frame_18)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        self.btn_keyboard.toggled['bool'].connect(self.frame_15.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lNome.setText(_translate("Form", "Nome:"))
        self.txtNome.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lSobrenome.setText(_translate("Form", "Sobrenome:"))
        self.txtSobrenome.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.l_CPF.setText(_translate("Form", "CPF:"))
        self.txtCPF.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.l_tel.setText(_translate("Form", "Telefone:"))
        self.txtTel.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.l_email.setText(_translate("Form", "E-mail:"))
        self.txtEmail.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnVoltar.setText(_translate("Form", "Voltar"))
        self.btn_register.setText(_translate("Form", "Registrar"))
        self.key_x.setText(_translate("Form", "x"))
        self.key_a.setText(_translate("Form", "a"))
        self.key_3.setText(_translate("Form", "3"))
        self.key_z.setText(_translate("Form", "z"))
        self.key_q.setText(_translate("Form", "q"))
        self.key_e.setText(_translate("Form", "e"))
        self.key_1.setText(_translate("Form", "1"))
        self.key_2.setText(_translate("Form", "2"))
        self.key_c.setText(_translate("Form", "c"))
        self.key_w.setText(_translate("Form", "w"))
        self.key_d.setText(_translate("Form", "d"))
        self.key_s.setText(_translate("Form", "s"))
        self.key_caps.setText(_translate("Form", "CAPSLOCK"))
        self.key_f.setText(_translate("Form", "f"))
        self.key_m.setText(_translate("Form", "m"))
        self.key_u.setText(_translate("Form", "u"))
        self.key_r.setText(_translate("Form", "r"))
        self.key_7.setText(_translate("Form", "7"))
        self.key_v.setText(_translate("Form", "v"))
        self.key_5.setText(_translate("Form", "5"))
        self.key_t.setText(_translate("Form", "t"))
        self.key_g.setText(_translate("Form", "g"))
        self.key_j.setText(_translate("Form", "j"))
        self.key_4.setText(_translate("Form", "4"))
        self.key_6.setText(_translate("Form", "6"))
        self.key_space.setText(_translate("Form", "Space"))
        self.key_h.setText(_translate("Form", "h"))
        self.key_y.setText(_translate("Form", "y"))
        self.key_n.setText(_translate("Form", "n"))
        self.key_b.setText(_translate("Form", "b"))
        self.key_l.setText(_translate("Form", "l"))
        self.key_c_.setText(_translate("Form", "ç"))
        self.key_ar.setText(_translate("Form", "@"))
        self.key_pt.setText(_translate("Form", "."))
        self.key_und.setText(_translate("Form", "_"))
        self.key_p.setText(_translate("Form", "p"))
        self.key_i.setText(_translate("Form", "i"))
        self.key_o.setText(_translate("Form", "o"))
        self.key_k.setText(_translate("Form", "k"))
        self.key_9.setText(_translate("Form", "9"))
        self.key_0.setText(_translate("Form", "0"))
        self.key_8.setText(_translate("Form", "8"))
#import register_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
